#!/usr/bin/env python3
"""Manage the translation-gap issue fed by the mirror's translation audit.

The hourly update workflow runs ``audit_translations.py`` against the freshly
built catalog and hands the findings JSON to ``sync``, which creates the issue
when gaps exist, edits the existing one only when its content changed (so
mostly-clean runs do not spam the timeline), and closes it once the audit
passes. ``open`` and ``close`` remain for manual use.

All GitHub access goes through the ``gh`` CLI with GITHUB_TOKEN set; every
``gh`` call is injectable, which keeps the decision logic unit-testable.

    python translation_issue.py sync findings.json   # hourly workflow
    python translation_issue.py open findings.json   # manual
    python translation_issue.py close                # manual
"""

import json
import os
import subprocess
import sys

ISSUE_TITLE = "Translation audit: add-ons still publishing non-English text"
ISSUE_LABEL = "translation-gap"
ISSUE_LABEL_COLOR = "e99695"
LABEL_DESCRIPTION = "Add-ons the mirror still publishes without English metadata"


def default_gh(args):
    """Run one gh CLI command and return (returncode, stdout)."""
    completed = subprocess.run(
        ["gh", *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return completed.returncode, completed.stdout


def _fenced(text):
    """Wrap text in a code fence long enough to survive backticks inside it."""
    fence = "```"
    while fence in text:
        fence += "`"
    return f"{fence}\n{text}\n{fence}"


#: GitHub rejects issue bodies over 65,536 characters, and then every hourly
#: create or edit fails. Stay under it with room for the closing lines.
MAX_BODY_CHARS = 60000


def render_body(findings, repository):
    """Render findings as the deterministic issue body."""
    count = len(findings)
    noun = "add-on" if count == 1 else "add-ons"
    header = [
        f"The translation audit found {count} {noun} still publishing "
        "non-English text in the live mirror.",
        "",
        "To fix: add an English `summary` and `description` for each add-on "
        "ID below to `translations.json`, then let the next hourly build "
        "publish them. `audit_translations.py` documents the detection "
        "rules; borrow style from the existing entries.",
        "",
        f"{len(findings)} untranslated {noun}:",
        "",
    ]
    footer = (
        "<sub>Generated by the mirror's "
        f"[hourly update workflow](https://github.com/{repository}/"
        "actions/workflows/update.yml). This issue closes "
        "automatically once the audit passes.</sub>"
    )
    body = "\n".join(header) + "\n"
    shown = 0
    for finding in findings:
        source = finding.get("sourceURL") or "no source URL"
        lines = [f"### `{finding['addonId']}` ({source})", ""]
        for field, detail in finding["fields"].items():
            text = " ".join((detail["text"] or "").split())
            if len(text) > 600:
                text = text[:597] + "..."
            lines.append(f"- `{field}` [{detail['reason']}]:")
            lines.append("")
            lines.append("  " + _fenced(text).replace("\n", "\n  "))
        lines.append("")
        block = "\n".join(lines) + "\n"
        if len(body) + len(block) + len(footer) + 200 > MAX_BODY_CHARS:
            break
        body += block
        shown += 1
    if shown < count:
        body += (
            f"...and {count - shown} more, left out to fit GitHub's issue "
            "size limit. Run `python audit_translations.py` for the full "
            "list.\n\n"
        )
    return body + footer


def find_open_issue(gh=default_gh, repository=None):
    """Return the number of the open gap issue, or None when there is none."""
    repository = repository or os.environ["GITHUB_REPOSITORY"]
    # List and match locally rather than --search: GitHub's issue search
    # index lags newly created issues by minutes, so a run that follows a
    # create too closely would not find it and open a duplicate.
    code, out = gh(
        [
            "issue", "list",
            "--repo", repository,
            "--state", "open",
            "--limit", "200",
            "--json", "number,title",
        ]
    )
    if code != 0:
        raise RuntimeError(f"gh issue list failed: {out}")
    for issue in json.loads(out or "[]"):
        if issue.get("title") == ISSUE_TITLE:
            return issue["number"]
    return None


def ensure_label(gh=default_gh, repository=None):
    """Create the gap label; an existing label makes the create fail, which is fine."""
    repository = repository or os.environ["GITHUB_REPOSITORY"]
    gh(
        [
            "label", "create", ISSUE_LABEL,
            "--repo", repository,
            "--description", LABEL_DESCRIPTION,
            "--color", ISSUE_LABEL_COLOR,
        ]
    )


def open_issue(findings_path, gh=default_gh, repository=None):
    """Create or update the gap issue from a findings JSON file."""
    repository = repository or os.environ["GITHUB_REPOSITORY"]
    with open(findings_path, "r", encoding="utf-8") as handle:
        findings = json.load(handle)
    body = render_body(findings, repository)
    number = find_open_issue(gh, repository)
    if number is None:
        ensure_label(gh, repository)
        code, out = gh(
            [
                "issue", "create",
                "--repo", repository,
                "--title", ISSUE_TITLE,
                "--body", body,
                "--label", ISSUE_LABEL,
            ]
        )
        if code != 0:
            raise RuntimeError(f"gh issue create failed: {out}")
        print(f"Opened the translation-gap issue: {out.strip()}")
        return
    code, out = gh(
        ["issue", "view", str(number), "--repo", repository, "--json", "body"]
    )
    if code == 0:
        current = json.loads(out or "{}").get("body", "")
        if current == body:
            print(f"Issue #{number} already matches the current findings.")
            return
    code, out = gh(
        ["issue", "edit", str(number), "--repo", repository, "--body", body]
    )
    if code != 0:
        raise RuntimeError(f"gh issue edit failed: {out}")
    print(f"Updated issue #{number} with the current findings.")


def close_issue(gh=default_gh, repository=None):
    """Close the gap issue when the audit no longer finds untranslated text."""
    repository = repository or os.environ["GITHUB_REPOSITORY"]
    number = find_open_issue(gh, repository)
    if number is None:
        print("No open translation-gap issue; nothing to close.")
        return
    code, out = gh(
        [
            "issue", "close", str(number),
            "--repo", repository,
            "--comment",
            "The translation audit no longer finds untranslated "
            "add-ons; closing automatically.",
        ]
    )
    if code != 0:
        raise RuntimeError(f"gh issue close failed: {out}")
    print(f"Closed issue #{number}.")


#: Prefix of the run-log lines the Muse cloud agent greps for. See AGENTS.md
#: "Muse cloud check". Changing it strands that agent: update both together.
QUEUE_LOG_PREFIX = "TRANSLATION-QUEUE"


def log_queue(findings, out=None):
    """Write the translation queue into the workflow run log.

    The issue is the friendly view; the run log is the one that survives when
    ``gh`` cannot reach the issue (missing permission, API outage, a body
    GitHub refuses). The Muse cloud agent reads these lines from the latest
    update-mirror run and adds the English itself. One JSON object per line,
    in full: the issue body truncates long text, this does not. ASCII-escaped
    JSON, so no console encoding can break the step; parsing restores the text.
    """
    out = out or sys.stdout
    if not findings:
        print(f"{QUEUE_LOG_PREFIX}-EMPTY", file=out)
        return
    print(f"{QUEUE_LOG_PREFIX}-BEGIN count={len(findings)}", file=out)
    for finding in findings:
        print(
            f"{QUEUE_LOG_PREFIX} "
            + json.dumps(finding, separators=(",", ":")),
            file=out,
        )
    print(f"{QUEUE_LOG_PREFIX}-END", file=out)
    # An annotation shows in `gh run view` without downloading the full log.
    print(
        f"::warning title=Translation queue::{len(findings)} add-on(s) still "
        f"publish non-English text; the {QUEUE_LOG_PREFIX} lines in this log "
        "list them for the Muse cloud check",
        file=out,
    )


def sync_issue(findings_path, gh=default_gh, repository=None):
    """Make the gap issue match a findings file: open, update, or close.

    The queue is written to the run log first, so it is recorded even when
    every ``gh`` call below fails.

    A missing findings file raises instead of closing, because a crashed
    audit must never close an issue that may still describe real gaps. The
    workflow absorbs that failure with continue-on-error and the next hourly
    run retries.
    """
    with open(findings_path, "r", encoding="utf-8") as handle:
        findings = json.load(handle)
    log_queue(findings)
    try:
        if findings:
            open_issue(findings_path, gh, repository)
        else:
            close_issue(gh, repository)
    except Exception as exc:
        # An annotation is one line; gh's output often is not.
        reason = " ".join(str(exc).split()) or type(exc).__name__
        print(
            f"::error title=Translation issue not updated::{reason}. The "
            f"{QUEUE_LOG_PREFIX} lines above are the queue of record.",
        )
        raise


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    valid = (
        len(argv) == 2 and argv[0] in ("sync", "open")
        or len(argv) == 1 and argv[0] == "close"
    )
    if not valid:
        print(__doc__, file=sys.stderr)
        return 2
    if argv[0] == "close":
        close_issue()
    else:
        handler = sync_issue if argv[0] == "sync" else open_issue
        handler(argv[1])
    return 0


if __name__ == "__main__":
    sys.exit(main())
